kind: pipeline
name: fuckoff.stream

steps:
- name: build-app
  image: node
  commands:
  - npm install

- name: docker  
  image: plugins/docker
  settings:
    repo: willebergh/fuckoff.stream
    tags:
    - latest
    - "1.0"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
