kind: pipeline
name: willebergh.io

steps:
- name: build-app
  image: node
  commands:
  - npm install

- name: build-image
  image: docker:dind
  commands:
  - docker build .

trigger:
  branch:
  - master
  event:
  - push