language: node_js

node_js:
  - "stable"

services:
  - docker

jobs:
  include:
    - stage: Install Dependencies
      script:
        - npm install
    
    - stage: Build App
      script:
        - mkdir build
        - cp -r public build/public
        - cp package*.json build
        - cp server.js build

    - stage: Build & Push Docker Image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t "$DOCKER_USERNAME"/fuckoff.stream:latest .
        - docker push $DOCKER_USERNAME/fuckoff.stream:latest
